import { useEffect, useState } from 'react';
import Icon from '../Icon';

export default function RecordModal({ open, type, record, clients = [], quotes = [], onClose, onSave }) {
  const [draft, setDraft] = useState(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => { if (open) { setDraft(record ? { ...record } : null); setError(''); } }, [open, record]);
  if (!open || !draft) return null;

  async function submit(event) {
    event.preventDefault(); setSaving(true); setError('');
    try { await onSave(draft); onClose(); } catch (saveError) { setError(saveError.message || 'Unable to save.'); } finally { setSaving(false); }
  }

  const title = type === 'client' ? 'client' : type === 'job' ? 'job' : type === 'payment' ? 'payment' : 'activity';
  return <div className="crm-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <form className="crm-modal record-modal" onSubmit={submit}>
      <header className="crm-modal-head"><div><p className="eyebrow">{record?.id ? 'Edit' : 'Add'} record</p><h2>{title}</h2></div><button type="button" className="crm-icon-button" onClick={onClose}><Icon name="close"/></button></header>
      <div className="crm-modal-body">
        {error ? <div className="manager-error">{error}</div> : null}
        {type === 'client' ? <>
          <div className="crm-form-grid two"><label>Company / organization<input value={draft.company_name || ''} onChange={(e) => setDraft({ ...draft, company_name: e.target.value })}/></label><label>Primary contact<input value={draft.primary_contact_name || ''} onChange={(e) => setDraft({ ...draft, primary_contact_name: e.target.value })} required/></label><label>Email<input type="email" value={draft.email || ''} onChange={(e) => setDraft({ ...draft, email: e.target.value })} required/></label><label>Phone<input value={draft.phone || ''} onChange={(e) => setDraft({ ...draft, phone: e.target.value })}/></label><label>Status<select value={draft.status || 'active'} onChange={(e) => setDraft({ ...draft, status: e.target.value })}><option value="prospect">Prospect</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>
          <h3 className="crm-form-subhead">Billing address</h3><div className="crm-form-grid two"><label>Address<input value={draft.billing_address_line_1 || ''} onChange={(e) => setDraft({ ...draft, billing_address_line_1: e.target.value })}/></label><label>Address line 2<input value={draft.billing_address_line_2 || ''} onChange={(e) => setDraft({ ...draft, billing_address_line_2: e.target.value })}/></label><label>City<input value={draft.billing_city || ''} onChange={(e) => setDraft({ ...draft, billing_city: e.target.value })}/></label><label>State<input maxLength="2" value={draft.billing_state || 'FL'} onChange={(e) => setDraft({ ...draft, billing_state: e.target.value.toUpperCase() })}/></label><label>ZIP<input value={draft.billing_zip || ''} onChange={(e) => setDraft({ ...draft, billing_zip: e.target.value })}/></label></div><label>Internal notes<textarea value={draft.notes || ''} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label>
        </> : null}
        {type === 'job' ? <>
          <div className="crm-form-grid two"><label>Client<select value={draft.client_id || ''} onChange={(e) => setDraft({ ...draft, client_id: e.target.value })} required><option value="">Choose client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.company_name || client.primary_contact_name}</option>)}</select></label><label>Job number<input value={draft.job_number || ''} readOnly/></label><label className="span-two">Project title<input value={draft.title || ''} onChange={(e) => setDraft({ ...draft, title: e.target.value })} required/></label><label>Status<select value={draft.status || 'scheduled'} onChange={(e) => setDraft({ ...draft, status: e.target.value })}>{['planning', 'scheduled', 'in_progress', 'waiting', 'completed', 'canceled'].map((status) => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></label><label>Contract amount ($)<input type="number" min="0" step="0.01" value={draft.contract_amount_dollars ?? ''} onChange={(e) => setDraft({ ...draft, contract_amount_dollars: e.target.value })}/></label><label>Start date<input type="date" value={draft.start_date || ''} onChange={(e) => setDraft({ ...draft, start_date: e.target.value })}/></label><label>Target completion<input type="date" value={draft.target_completion_date || ''} onChange={(e) => setDraft({ ...draft, target_completion_date: e.target.value })}/></label></div>
          <label>Description<textarea value={draft.description || ''} onChange={(e) => setDraft({ ...draft, description: e.target.value })}/></label><h3 className="crm-form-subhead">Project location</h3><div className="crm-form-grid two"><label>Address<input value={draft.project_address || ''} onChange={(e) => setDraft({ ...draft, project_address: e.target.value })}/></label><label>City<input value={draft.city || ''} onChange={(e) => setDraft({ ...draft, city: e.target.value })}/></label><label>State<input maxLength="2" value={draft.state || 'FL'} onChange={(e) => setDraft({ ...draft, state: e.target.value.toUpperCase() })}/></label><label>ZIP<input value={draft.zip_code || ''} onChange={(e) => setDraft({ ...draft, zip_code: e.target.value })}/></label></div><label>Internal notes<textarea value={draft.notes || ''} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label>
        </> : null}
        {type === 'payment' ? <div className="crm-form-grid two"><label>Amount ($)<input type="number" min="0.01" step="0.01" value={draft.amount_dollars || ''} onChange={(e) => setDraft({ ...draft, amount_dollars: e.target.value })} required/></label><label>Paid on<input type="date" value={draft.paid_on || ''} onChange={(e) => setDraft({ ...draft, paid_on: e.target.value })} required/></label><label>Method<select value={draft.method || 'check'} onChange={(e) => setDraft({ ...draft, method: e.target.value })}>{['check', 'ach', 'card', 'cash', 'wire', 'other'].map((method) => <option key={method} value={method}>{method.toUpperCase()}</option>)}</select></label><label>Reference<input value={draft.reference || ''} onChange={(e) => setDraft({ ...draft, reference: e.target.value })} placeholder="Check #, ACH ID…"/></label><label className="span-two">Notes<textarea value={draft.notes || ''} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label></div> : null}
        {type === 'activity' ? <div className="crm-form-grid two"><label>Activity type<select value={draft.activity_type || 'note'} onChange={(e) => setDraft({ ...draft, activity_type: e.target.value })}>{['note', 'call', 'email', 'meeting', 'site_visit', 'job_update', 'other'].map((activity) => <option value={activity} key={activity}>{activity.replaceAll('_', ' ')}</option>)}</select></label><label>Client<select value={draft.client_id || ''} onChange={(e) => setDraft({ ...draft, client_id: e.target.value })}><option value="">General activity</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.company_name || client.primary_contact_name}</option>)}</select></label><label className="span-two">Summary<input value={draft.summary || ''} onChange={(e) => setDraft({ ...draft, summary: e.target.value })} required/></label><label className="span-two">Details<textarea value={draft.details || ''} onChange={(e) => setDraft({ ...draft, details: e.target.value })}/></label></div> : null}
      </div>
      <footer className="crm-modal-actions"><button type="button" className="crm-secondary-button" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? 'Saving…' : `Save ${title}`} <Icon name="arrow"/></button></footer>
    </form>
  </div>;
}
